name: Bump to latest version
on:
  workflow_dispatch:

jobs:
  bump-version:
    name: Bump to latest version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Update to latest parent version
        run: mvn -f ./src/pom.xml versions:update-parent -DallowSnapshots=true
      - name: Get current version
        id: getversion
        run: |
          version=$(mvn -f src/pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo ::set-output name=version::$version
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.3.0
        with:
          token: ${{ secrets.GH_TOKEN_PAT }}
          commit-message: "Bump to version ${{ steps.getversion.outputs.version }}"
          committer: AutoBumper <autobumper@autobumper>
          author: AutoBumper <autobumper@autobumper>
          branch: "bump-${{ steps.getversion.outputs.version }}"
          title: "Bump to version ${{ github.event.inputs.version }}"
          body: ""
          
